# Generated by Django 6.0.4 on 2026-05-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('source_name', models.CharField(default='Hetauda Khabar', max_length=120)),
                ('original_url', models.URLField(unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('local', 'Local News'), ('development', 'Development'), ('public_notice', 'Public Notice'), ('politics', 'Politics'), ('event', 'Event'), ('other', 'Other')], default='local', max_length=50)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
